#General
general:
  begin-spawning-stars-time: 13000
  end-spawning-stars-time: 23000
  new-moon-meteor-shower: true
  debug: false

# Shooting stars
shooting-stars:
  enabled: true
  per-minute: 6
  pper-minute-during-meteor-showers: 15
  min-height: 130
  max-height: 160
  summon-text: "Make a wish!"

# Falling stars
falling-stars:
  enabled: true
  per-minute: 0.2
  per-minute-during-meteor-showers: 0.3
  radius: 10
  sound-enabled: true
  volume: 6
  spark-time: 200
  experience: 100
  loots:
    diamond: 60
    emerald: 20
    fire_charge: 20
  summon-text: "Make a wish!"

# Red falling stars
red-falling-stars:
  enabled: true
  per-minute: 0.5
  per-minute-during-meteor-showers: 0.1
  radius: 50
  summon-text: "&cRun!"
  mobs:
    mob_1:
      name: "Wither de rancœur"
      type: WITHER_SKELETON
      health: 100
      equipment:
        head:
          type: NETHERITE_HELMET
          droppable: false
        hand:
          type: STONE_SWORD
          enchantements:
            - name: FIRE_ASPECT
              level: 1
          droppable: false
